### ISSUE TITLE
Dataloader takes too long to load

### ISSUE THREAD

**Issue by wangdazhong1112** [vefalun/HTFormer#1]
Why does the dataloader take so long? It takes about half an hour. I'm a 3060ti graphics card with 16g memory

**Comment by vefalun** [comment]
Thank you for using HTNet. For reference, the dataloader takes about 10 seconds.

**Comment by wangdazhong1112** [comment]
Thank you for your answer！
What is your configuration of graphics card and memory？
How about jumping into this cycle? My computer has been here for a long time. Debugging can't be carried out
![image](https://user-images.githubusercontent.com/119930848/224490189-e9302012-a1a9-4a18-88d4-29f683483efc.png)

**Comment by vefalun** [comment]
Please send your wechat  account to cjl@stu.pku.edu.cn，I will help you out

**Comment by wangdazhong1112** [comment]
okay, thank you. I will send email via student email

**Comment by jianlai123-123** [comment]
Hello, can you achieve the effect in the paper by retraining the model without adding the refine parameter? @wangdazhong1112

**Comment by wangdazhong1112** [comment]
> 



> 你好，请问在不加refine参数的情况下重新训练模型能达到论文中的效果吗？@wangdazhong1112

是的，大概差距为0.5左右

**Comment by jianlai123-123** [comment]
请问是直接运行python main.py --train 吗？我直接运行的话，效果达不到，而且学习率不是显示5个epoch下降一次，而是一个epoch就下降一次。还有如果要使用优化的话，是怎么运行的呢。期待您的回复，十分感谢。 @wangdazhong1112

**Comment by vefalun** [comment]
是运行python main.py --train，学习率是每个epoch变成前一个epoch学习率的95%，每五个epoch下降50%，优化部分我们采用了和mgcn一样的方式，可以参考他们的方法



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 21, 2023 20:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vefalun/HTNet] Dataloader takes too long to load (Issue #1)




 
请问是直接运行python main.py --train 吗？我直接运行的话，效果达不到，而且学习率不是显示5个epoch下降一次，而是一个epoch就下降一次。还有如果要使用优化的话，是怎么运行的呢。期待您的回复，十分感谢。 @wangdazhong1112

**Comment by wangdazhong1112** [comment]
> 请问是直接运行python main.py --train 吗？我直接运行的话，效果达不到，而且学习率不是显示5个epoch下降一次，而是一个epoch就下降一次。还有如果要使用优化的话，是怎么运行的呢。期待您的回复，十分感谢。 @wangdazhong1112

python main.py --train默认的是使用cpn检测器数据集，需要改成gt真值的话可以通过修改opt.py文件，也可以命令行加上-k gt，使用refine进行优化可以在opt中修改默认值，改为开启。

**Comment by jianlai123-123** [comment]
你好，我直接运行python main.py --train的话，得到这样的结果。
<img width="722" alt="4" src="https://user-images.githubusercontent.com/117512033/226603321-5ccab775-ec54-4e5c-a1b2-e02ae2c55a50.png">
<img width="740" alt="3" src="https://user-images.githubusercontent.com/117512033/226603374-271cfd43-a644-46c4-bad6-7e545759849e.png">
<img width="723" alt="21" src="https://user-images.githubusercontent.com/117512033/226603424-58c71e11-5309-4a8c-bd72-8ad455faf749.png">

**Comment by vefalun** [comment]
最终性能在不同环境，不同显卡中都不一样，48.8-49.5之间属于正常波动



---Original---
From: ***@***.***&gt;
Date: Tue, Mar 21, 2023 20:17 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vefalun/HTNet] Dataloader takes too long to load (Issue #1)




 
你好，我直接运行python main.py --train的话，得到这样的结果。

**Comment by jianlai123-123** [comment]
你好，了解。如果是要使用优化的话。是不是把第一次没有使用优化参数训练得到的结果当作预训练模型。然后执行python main.py --train --lr_refine 1e-5 -k 'cpn_ft_h36m_dbb' -n 'your_model' --refine --refine_train_reload --previous_dir './ckpt/your_model' --previous_refine_name '预训练模型名称'。

**Comment by wangdazhong1112** [comment]
> 你好，了解。如果是要使用优化的话。是不是把第一次没有使用优化参数训练得到的结果当作预训练模型。然后执行python main.py --train --lr_refine 1e-5 -k 'cpn_ft_h36m_dbb' -n 'your_model' --refine --refine_train_reload --previous_dir './ckpt/your_model' --previous_refine_name '预训练模型名称'。

我并没有跑refine网络，不过你应该是对的

**Comment by jianlai123-123** [comment]
好的，谢谢。按照MGCN方法的话，把第一次跑的当作预训练模型，然后第二次使用refine，并且把第一次模型放进来，前五个epoch的话，结果很高，loss也很高。我就没再继续了。后面我还是用这样的方法跑30个epoch，看看具体的效果。

**Comment by jianlai123-123** [comment]
你好，请问你知道怎么在 MPI-INF-3DHP数据集上面训练和测试吗？ @wangdazhong1112

**Comment by wangdazhong1112** [comment]
> 你好，请问你知道怎么在 MPI-INF-3DHP数据集上面训练和测试吗？ @wangdazhong1112

作者并没有给出相关代码，但其他相关研究应该是有的，我正好想咨询一下你最后复现的效果是多少呢？和我一样，相较于论文大概有0.3的误差吗？

**Comment by jianlai123-123** [comment]
你问的是在MPI-INF-3DHP数据集上上面的结果吗？我没复现的出来，你要是复现出来，能分享一下代码吗？

**Comment by jianlai123-123** [comment]
你好，还有一个问题请教一下，就是在human数据集上面跑的时候，第二步是添加refine模块，我第一步得到的预训练模型在第二步加载不了，请问你是怎么解决的呢？

**Comment by wangdazhong1112** [comment]
> 你问的是在MPI-INF-3DHP数据集上上面的结果吗？我没复现的出来，你要是复现出来，能分享一下代码吗？

不是，我问的是Human3.6m的结果，MPI-INF-3DHP的我并没有去跑，所以没有MPI-INF-3DHP的数据处理代码

**Comment by jianlai123-123** [comment]
我跑的时候，没有refine模块就相差挺大的，然后第二次跑添加refine模块没跑成功，第一次跑的文件加载不了

**Comment by wangdazhong1112** [comment]
> 我跑的时候，没有refine模块就相差挺大的，然后第二次跑添加refine模块没跑成功，第一次跑的文件加载不了

好的，感谢。我如果后续需要用到MPI-INF-3DHP，并且找到相关数据集处理代码的话，会分享给你的

**Comment by jianlai123-123** [comment]
好的，多谢。

**Comment by jianlai123-123** [comment]
你好，请问怎么私聊你@wangdazhong1112

**Comment by wangdazhong1112** [comment]
> 你好，请问怎么私聊你@wangdazhong1112

你好，你是找到了MPI-INF-3DHP数据集处理代码了吗？如果可以发给我的话，可以发送私人微信到wdz2345665432@qq.com这个邮箱中
