### ISSUE TITLE
Code problems

### ISSUE THREAD

**Issue by jianlai123-123** [vefalun/HTFormer#2]
Hello, in the GBI module, MSA and LN are passed first in the paper diagram. But does the code seem to be reversed? x_ attn = x_ attn + self.drop_ path(self.attn(self.norm_attn(x_attn))).Looking forward to your reply, thank you.

**Comment by vefalun** [comment]
We checked the figure, you are right. The GBI module is just a general Transformer module, the LN should be drawn in front of the MSA module in the figure, we are very grateful for your useful and careful suggestion！
